/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Articles } from "./Articles";

export { Articles__factory } from "./factories/Articles__factory";
